version: '0.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5002:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/PGDATA
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - 5001:5001
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:5001'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      'db':
        condition: service_healthy
  frontend:
    build: ../codeless4-front
    volumes:
      - ../codeless4/src:/src
    ports:
      - 3000:3000
    depends_on:
      'backend' :
        condition: service_healthy
  
