version: "2.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5002:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/PGDATA
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    volumes:
      - ./hydra.css:/var/www/html/adminer.css
    links:
      - db
  backend:
    build: .
    environment:
      - PORT=7008
    volumes:
      - ./src:/app/src
    ports:
      - 5001:5001
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:5001'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      "db":
        condition: service_healthy
  frontend:
    build: ../codeless4-front
    volumes:
      - ../codeless4-front/:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    depends_on:
      "backend":
        condition: service_healthy
  compiler:
    build: ./compiler
    ports:
      - 7008:7008
    depends_on:
      "backend":
        condition: service_healthy
