version: "2.1"
services:
  db-test:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      PGUSER: "postgres"
      PG_PORT: 5432
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  backend-test:
    build: .
    env_file:
      - ./.env.test
    volumes:
      - ./src:/app/src
    ports:
      - 5002:5002
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:5002'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      "db-test":
        condition: service_healthy
