name: jest-ci

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: "Create main env file"
        run: |
          touch .env.test
          echo "${{ secrets.MAIN_ENV_FILE }}" > .env.test
      - name: Check out code
        uses: actions/checkout@v3
      - name: Goto server and run tests
        run: npm i && npm run test

  deploy-staging:
    needs: test-back
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/codeless4-backend:staging

  deploy-production:
    needs: test-back
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/codeless4-backend:latest

